events {}

http {
  # Логи по желанию
  access_log /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log;

  client_max_body_size 500M;

  upstream client {
    server client:80;
  }

  upstream admin {
    server admin:80;
  }

  upstream backend {
    server backend:3000;
  }

  server {
    listen 80;
    server_name trello-analog.ru;
    # для обновления сертификата
    location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
  } # для обновления сертификата на хосте
    location / {
      return 301 https://$host$request_uri;
    }
  }

    # Все запросы к API шлём на backend
  server {
    listen 443 ssl;
    server_name trello-analog.ru trello-analog.ru;

    # Nginx uses a local cert bundle. It will be self-signed until Certbot issues a real one.
    ssl_certificate     /etc/letsencrypt/live/$NGINX_CERT_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$NGINX_CERT_DOMAIN/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Let’s Encrypt HTTP-01 challenge (на случай редиректа на https)
    location ^~ /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location /apiback/ {
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
      proxy_pass http://admin/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://client;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}